# -*- coding: utf-8 -*-
"""Scam_Detection_Using_Explainable_Artificial_Intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135E1O9-YBKknsZMxsz1EID3aqdIgo0DN

**Steps To Understand The Code**
1. Importing the important libreries
2. Loading both the datasets
3. Printing the first 5 rows of both the datasets
4. Cleaning the sms dataset
5. Cleaning the email dataset
6. Text preprocessing (only lowercase + cleaning)
7. Convert text to numbers (tf-idf)
8. Train test split for both sms and email
9. Logistic regression training + evaluation sms
10. Random forest — training & evaluation (sms)
11. Xgboost — improved training & evaluation (sms)
12. Printing everything of sms machine learning
13. Logistic regression (email)
14. Random forest (email)
15. Xgboost (email)
16. Printing everything of email machine learning
17. Creating hybrid model for sms
18. Printing everything for hybrid model sms
19. Creating hybrid model for email
20. Printing everything for hybrid model email
21. Shap for sms
22. Shap for email
23. Lime for sms
24. Lime for email
"""

#Step - 01 Importing the important libreries
!pip install lime
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Step - 02 Loading both the datasets
sms_df = pd.read_excel("sms spam.xlsx")
email_df = pd.read_excel("Email spam.xlsx")

# Step - 03 Printing the first 5 rows of both the datasets
sms_df.head()
email_df.head()

# Step - 04 CLEAN SMS DATASET
# Keep only required columns
sms_df = sms_df[['v1', 'v2']]
# Rename columns
sms_df.columns = ['label', 'text']
# Convert labels to numbers
sms_df['label'] = sms_df['label'].str.strip().str.lower().map({'ham': 0, 'spam': 1})
#To verify SMS cleaned successfully
sms_df['label'].value_counts()

# Step - 05 Clean Email dataset
# Keep only required columns
email_df = email_df[['Email Text', 'Email Type']]
# Rename columns to match SMS dataset
email_df.columns = ['text', 'label']
# Convert labels to numbers
email_df['label'] = (email_df['label'].str.strip().str.lower().map({'safe email': 0, 'phishing email': 1}))
#To verify Email cleaned successfully
email_df['label'].value_counts()

# Step - 06 TEXT PREPROCESSING (only lowercase + cleaning)
#Tools initialized
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
# Creating the text cleaning function
def clean_text(text):
    if pd.isna(text):
          return ""
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(word)
             for word in words
             if word not in stop_words]
    return " ".join(words)
# Text cleaning function working or not
clean_text("Congratulations! You have WON 1000 rupees!!!")
# Applying the text cleaning function
sms_df['clean_text'] = sms_df['text'].apply(clean_text)
email_df['clean_text'] = email_df['text'].apply(clean_text)
# Verifying Text preprocessing applied or not
sms_df[['text', 'clean_text']].head()
email_df[['text', 'clean_text']].head()

# Step - 07 Convert text to numbers (TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer
# Separate TF-IDF vectorizers
tfidf_sms = TfidfVectorizer(max_features=5000)
tfidf_email = TfidfVectorizer(max_features=5000)
# SMS TF-IDF
X_sms = tfidf_sms.fit_transform(sms_df['clean_text'])
y_sms = sms_df['label']
# Email TF-IDF
X_email = tfidf_email.fit_transform(email_df['clean_text'])
y_email = email_df['label']

# Step - 08 Train-Test Split for both sms and email
from sklearn.model_selection import train_test_split
# SMS train-test split
X_sms_train, X_sms_test, y_sms_train, y_sms_test = train_test_split(X_sms, y_sms, test_size=0.2, random_state=42)
X_sms_train.shape, X_sms_test.shape
#Email train-test split
email_df = email_df.dropna(subset=['label'])
X_email = tfidf_email.fit_transform(email_df['clean_text'])
y_email = email_df['label']
X_email_train, X_email_test, y_email_train, y_email_test = train_test_split(X_email, y_email, test_size=0.2, random_state=42)

# Step - 09 Logistic regression training + evaluation sms
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
lr_sms = LogisticRegression(max_iter=1000)
lr_sms.fit(X_sms_train, y_sms_train)
y_sms_pred = lr_sms.predict(X_sms_test)
print("SMS Logistic Regression Accuracy:")
print(accuracy_score(y_sms_test, y_sms_pred))
print("\nClassification Report:")
print(classification_report(y_sms_test, y_sms_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_sms_test, y_sms_pred))

# Step - 10 Random forest — training & evaluation (sms)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
rf_sms = RandomForestClassifier(n_estimators=400,random_state=42,class_weight='balanced')
rf_sms.fit(X_sms_train, y_sms_train)
y_sms_pred_rf = rf_sms.predict(X_sms_test)
print("SMS Random Forest Accuracy:")
print(accuracy_score(y_sms_test, y_sms_pred_rf))
print("\nClassification Report:")
print(classification_report(y_sms_test, y_sms_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_sms_test, y_sms_pred_rf))

# Step - 11 Xgboost — improved training & evaluation (sms)
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Calculate class imbalance ratio for spam vs ham
spam_count = sum(y_sms_train == 1)
ham_count = sum(y_sms_train == 0)
scale_pos_weight = ham_count / spam_count if spam_count > 0 else 1 # imbalance ratio
# Create XGBoost model with tuned hyperparameters
xgb_sms_tuned = XGBClassifier(n_estimators=600,learning_rate=0.05,max_depth=10,subsample=0.8,colsample_bytree=0.8,scale_pos_weight=scale_pos_weight,random_state=42,use_label_encoder=False,eval_metric='logloss')
# Train model
xgb_sms_tuned.fit(X_sms_train, y_sms_train)
# Predict on test set
y_sms_pred_xgb_tuned = xgb_sms_tuned.predict(X_sms_test)
# Evaluate performance
print("SMS XGBoost Tuned Accuracy:")
print(accuracy_score(y_sms_test, y_sms_pred_xgb_tuned))
print("\nClassification Report:")
print(classification_report(y_sms_test, y_sms_pred_xgb_tuned))
print("\nConfusion Matrix:")
print(confusion_matrix(y_sms_test, y_sms_pred_xgb_tuned))

# Step - 12 Printing everything of SMS machine learning
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, classification_report, accuracy_score
# Models dictionary
models = {"Logistic Regression": lr_sms,"Random Forest": rf_sms,"XGBoost": xgb_sms_tuned}
for name, model in models.items():
    y_pred = model.predict(X_sms_test)
    cm = confusion_matrix(y_sms_test, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"{name} - Confusion Matrix", fontsize=14)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
for name, model in models.items():
    y_proba = model.predict_proba(X_sms_test)[:,1]
    fpr, tpr, _ = roc_curve(y_sms_test, y_proba)
    auc = roc_auc_score(y_sms_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, color='blue', label=f"AUC = {auc:.3f}", linewidth=2)
    plt.plot([0,1], [0,1], 'k--')
    plt.title(f"{name} - ROC Curve", fontsize=14)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend(loc="lower right")
    plt.show()
results = []
for name, model in models.items():
    y_pred = model.predict(X_sms_test)
    accuracy = accuracy_score(y_sms_test, y_pred)
    report = classification_report(y_sms_test, y_pred, output_dict=True)
    f1 = report['macro avg']['f1-score']
    precision = report['macro avg']['precision']
    recall = report['macro avg']['recall']
    results.append({
        "Model": name,
        "Accuracy": f"{accuracy:.3f}",
        "F1-Score": f"{f1:.3f}",
        "Precision": f"{precision:.3f}",
        "Recall": f"{recall:.3f}"
    })
# Convert to DataFrame
results_df = pd.DataFrame(results)
# Plot table
fig, ax = plt.subplots(figsize=(8,2))
ax.axis('off')
tbl = ax.table(cellText=results_df.values,colLabels=results_df.columns,cellLoc='center',loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(12)
tbl.auto_set_column_width(range(len(results_df.columns)))
plt.title("Classification Metrics Table - SMS Spam Detection", fontsize=14, pad=10)
plt.show()
metrics = ["Accuracy","F1-Score","Precision","Recall"]
results_df_melt = results_df.melt(id_vars="Model", value_vars=metrics, var_name="Metric", value_name="Score")
# Convert score to float for plotting
results_df_melt["Score"] = results_df_melt["Score"].astype(float)
plt.figure(figsize=(8,5))
sns.barplot(data=results_df_melt, x="Metric", y="Score", hue="Model", palette="Set2")
plt.ylim(0,1)
plt.title("Comparison of Metrics for All Models", fontsize=14)
plt.ylabel("Score")
plt.show()

# Step-13 Logistic Regression (Email)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
lr_email = LogisticRegression(max_iter=1000)
lr_email.fit(X_email_train, y_email_train)
y_email_pred_lr = lr_email.predict(X_email_test)
print("Email Logistic Regression Accuracy:")
print(accuracy_score(y_email_test, y_email_pred_lr))
print("\nClassification Report:")
print(classification_report(y_email_test, y_email_pred_lr))
print("\nConfusion Matrix:")
print(confusion_matrix(y_email_test, y_email_pred_lr))

# Step-14 Random Forest (Email)
from sklearn.ensemble import RandomForestClassifier
rf_email = RandomForestClassifier(n_estimators=400,random_state=42,class_weight='balanced')
rf_email.fit(X_email_train, y_email_train)
y_email_pred_rf = rf_email.predict(X_email_test)
print("Email Random Forest Accuracy:")
print(accuracy_score(y_email_test, y_email_pred_rf))
print("\nClassification Report:")
print(classification_report(y_email_test, y_email_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_email_test, y_email_pred_rf))

# Step-15 XGBoost (Email)
from xgboost import XGBClassifier
# Handle class imbalance
phish_count = sum(y_email_train == 1)
safe_count = sum(y_email_train == 0)
scale_pos_weight_email = safe_count / phish_count if phish_count > 0 else 1
xgb_email_tuned = XGBClassifier(n_estimators=600,learning_rate=0.05,max_depth=10,subsample=0.8,colsample_bytree=0.8,scale_pos_weight=scale_pos_weight_email,random_state=42,use_label_encoder=False,eval_metric='logloss')
xgb_email_tuned.fit(X_email_train, y_email_train)
y_email_pred_xgb = xgb_email_tuned.predict(X_email_test)
print("Email XGBoost Tuned Accuracy:")
print(accuracy_score(y_email_test, y_email_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_email_test, y_email_pred_xgb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_email_test, y_email_pred_xgb))

# Step-16 Printing everything of Email machine learning
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, classification_report, accuracy_score
models_email = {"Logistic Regression": lr_email,"Random Forest": rf_email,"XGBoost": xgb_email_tuned}
for name, model in models_email.items():
    y_pred = model.predict(X_email_test)
    cm = confusion_matrix(y_email_test, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"{name} - Confusion Matrix (Email)", fontsize=14)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
for name, model in models_email.items():
    y_proba = model.predict_proba(X_email_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_email_test, y_proba)
    auc = roc_auc_score(y_email_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, color='blue', label=f"AUC = {auc:.3f}", linewidth=2)
    plt.plot([0,1], [0,1], 'k--')
    plt.title(f"{name} - ROC Curve (Email)", fontsize=14)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend(loc="lower right")
    plt.show()
results_email = []
for name, model in models_email.items():
    y_pred = model.predict(X_email_test)
    accuracy = accuracy_score(y_email_test, y_pred)
    report = classification_report(y_email_test, y_pred, output_dict=True)
    results_email.append({"Model": name,"Accuracy": f"{accuracy:.3f}","F1-Score": f"{report['macro avg']['f1-score']:.3f}","Precision": f"{report['macro avg']['precision']:.3f}","Recall": f"{report['macro avg']['recall']:.3f}"})
results_email_df = pd.DataFrame(results_email)
fig, ax = plt.subplots(figsize=(8,2))
ax.axis('off')
tbl = ax.table(cellText=results_email_df.values,colLabels=results_email_df.columns,cellLoc='center',loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(12)
tbl.auto_set_column_width(range(len(results_email_df.columns)))
plt.title("Classification Metrics Table - Email Phishing Detection", fontsize=14, pad=10)
plt.show()
metrics = ["Accuracy", "F1-Score", "Precision", "Recall"]
results_email_melt = results_email_df.melt(id_vars="Model",value_vars=metrics,var_name="Metric",value_name="Score")
results_email_melt["Score"] = results_email_melt["Score"].astype(float)
plt.figure(figsize=(8,5))
sns.barplot(data=results_email_melt,x="Metric",y="Score",hue="Model",palette="Set2")
plt.ylim(0,1)
plt.title("Comparison of Metrics for All Models (Email)", fontsize=14)
plt.ylabel("Score")
plt.show()

# Step - 17 creating hybrid model for SMS
from sklearn.ensemble import VotingClassifier
hybrid_sms = VotingClassifier(estimators=[('lr', lr_sms),('rf', rf_sms),('xgb', xgb_sms_tuned)],voting='soft')
hybrid_sms.fit(X_sms_train, y_sms_train)
y_sms_pred_hybrid = hybrid_sms.predict(X_sms_test)
print("SMS Hybrid Model Accuracy:")
print(accuracy_score(y_sms_test, y_sms_pred_hybrid))
print("\nClassification Report:")
print(classification_report(y_sms_test, y_sms_pred_hybrid))
print("\nConfusion Matrix:")
print(confusion_matrix(y_sms_test, y_sms_pred_hybrid))

# STEP-18: PRINTING EVERYTHING FOR HYBRID MODEL – SMS
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, classification_report, accuracy_score
models_sms_hybrid = {"Hybrid Model": hybrid_sms}
for name, model in models_sms_hybrid.items():
    y_pred = model.predict(X_sms_test)
    cm = confusion_matrix(y_sms_test, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"{name} - Confusion Matrix (SMS)", fontsize=14)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
for name, model in models_sms_hybrid.items():
    y_proba = model.predict_proba(X_sms_test)[:,1]
    fpr, tpr, _ = roc_curve(y_sms_test, y_proba)
    auc = roc_auc_score(y_sms_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, color='blue', label=f"AUC = {auc:.3f}", linewidth=2)
    plt.plot([0,1], [0,1], 'k--')
    plt.title(f"{name} - ROC Curve (SMS)", fontsize=14)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend(loc="lower right")
    plt.show()
results_sms_hybrid = []
for name, model in models_sms_hybrid.items():
    y_pred = model.predict(X_sms_test)
    accuracy = accuracy_score(y_sms_test, y_pred)
    report = classification_report(y_sms_test, y_pred, output_dict=True)
    results_sms_hybrid.append({"Model": name,"Accuracy": f"{accuracy:.3f}","F1-Score": f"{report['macro avg']['f1-score']:.3f}","Precision": f"{report['macro avg']['precision']:.3f}","Recall": f"{report['macro avg']['recall']:.3f}"})
results_sms_hybrid_df = pd.DataFrame(results_sms_hybrid)
fig, ax = plt.subplots(figsize=(8,2))
ax.axis('off')
tbl = ax.table(cellText=results_sms_hybrid_df.values,colLabels=results_sms_hybrid_df.columns,cellLoc='center',loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(12)
tbl.auto_set_column_width(range(len(results_sms_hybrid_df.columns)))
plt.title("Hybrid Model Metrics - SMS Scam Detection", fontsize=14, pad=10)
plt.show()

# Step 19 creating hybrid model for Email
hybrid_email = VotingClassifier(estimators=[('lr', lr_email),('rf', rf_email),('xgb', xgb_email_tuned)],voting='soft')
hybrid_email.fit(X_email_train, y_email_train)
y_email_pred_hybrid = hybrid_email.predict(X_email_test)
print("Email Hybrid Model Accuracy:")
print(accuracy_score(y_email_test, y_email_pred_hybrid))
print("\nClassification Report:")
print(classification_report(y_email_test, y_email_pred_hybrid))
print("\nConfusion Matrix:")
print(confusion_matrix(y_email_test, y_email_pred_hybrid))

# STEP-20: PRINTING EVERYTHING FOR HYBRID MODEL – EMAIL
models_email_hybrid = {"Hybrid Model": hybrid_email}
for name, model in models_email_hybrid.items():
    y_pred = model.predict(X_email_test)
    cm = confusion_matrix(y_email_test, y_pred)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f"{name} - Confusion Matrix (Email)", fontsize=14)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
for name, model in models_email_hybrid.items():
    y_proba = model.predict_proba(X_email_test)[:,1]
    fpr, tpr, _ = roc_curve(y_email_test, y_proba)
    auc = roc_auc_score(y_email_test, y_proba)
    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, color='blue', label=f"AUC = {auc:.3f}", linewidth=2)
    plt.plot([0,1], [0,1], 'k--')
    plt.title(f"{name} - ROC Curve (Email)", fontsize=14)
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend(loc="lower right")
    plt.show()
results_email_hybrid = []
for name, model in models_email_hybrid.items():
    y_pred = model.predict(X_email_test)
    accuracy = accuracy_score(y_email_test, y_pred)
    report = classification_report(y_email_test, y_pred, output_dict=True)
    results_email_hybrid.append({"Model": name,"Accuracy": f"{accuracy:.3f}","F1-Score": f"{report['macro avg']['f1-score']:.3f}","Precision": f"{report['macro avg']['precision']:.3f}","Recall": f"{report['macro avg']['recall']:.3f}"})
results_email_hybrid_df = pd.DataFrame(results_email_hybrid)
fig, ax = plt.subplots(figsize=(8,2))
ax.axis('off')
tbl = ax.table(cellText=results_email_hybrid_df.values,colLabels=results_email_hybrid_df.columns,cellLoc='center',loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(12)
tbl.auto_set_column_width(range(len(results_email_hybrid_df.columns)))
plt.title("Hybrid Model Metrics - Email Phishing Detection", fontsize=14, pad=10)
plt.show()

# Step - 21 SHAP FOR SMS (CORRECTED & SAFE)
import shap
# Take small dense samples (memory-safe)
X_sms_test_dense = X_sms_test[:200].toarray()
# Create SHAP explainer for XGBoost model
explainer_sms = shap.TreeExplainer(xgb_sms_tuned)
# NEW SHAP API (robust for latest versions)
shap_values_sms = explainer_sms(X_sms_test_dense)
# Summary plot
shap.summary_plot(shap_values_sms.values,X_sms_test_dense,feature_names=tfidf_sms.get_feature_names_out())
# Waterfall plot for one instance
shap.waterfall_plot(shap_values_sms[10])

# Step - 22 SHAP FOR EMAIL (CORRECTED & SAFE)
import shap
# Take small dense samples
X_email_test_dense = X_email_test[:200].toarray()
# Create SHAP explainer
explainer_email = shap.TreeExplainer(xgb_email_tuned)
# New SHAP API
shap_values_email = explainer_email(X_email_test_dense)
# Summary plot
shap.summary_plot(shap_values_email.values,X_email_test_dense,feature_names=tfidf_email.get_feature_names_out())
# Waterfall plot for one instance
shap.waterfall_plot(shap_values_email[5])

# Step - 23 LIME FOR SMS
from lime.lime_text import LimeTextExplainer
class_names = ['Ham', 'Spam']
explainer_sms_lime = LimeTextExplainer(class_names=class_names)
def sms_predict_proba(texts):
    texts_cleaned = [clean_text(t) for t in texts]
    texts_tfidf = tfidf_sms.transform(texts_cleaned)
    return hybrid_sms.predict_proba(texts_tfidf)
idx = 9  # you can change this
exp_sms = explainer_sms_lime.explain_instance(sms_df['text'].iloc[idx],sms_predict_proba,num_features=10)
exp_sms.show_in_notebook()

# Step - 24 LIME FOR EMAIL
class_names_email = ['Safe Email', 'Phishing Email']
explainer_email_lime = LimeTextExplainer(class_names=class_names_email)
def email_predict_proba(texts):
    texts_cleaned = [clean_text(t) for t in texts]
    texts_tfidf = tfidf_email.transform(texts_cleaned)
    return hybrid_email.predict_proba(texts_tfidf)
idx = 30  # change if you want
exp_email = explainer_email_lime.explain_instance(email_df['text'].iloc[idx],email_predict_proba,num_features=10)
exp_email.show_in_notebook()

from lime.lime_text import LimeTextExplainer
def predict_sms_feature(message, threshold=0.4):
    # --- Vectorize message ---
    cleaned = clean_text(message)
    vec = tfidf_sms.transform([cleaned])
    # --- Prediction ---
    spam_proba = hybrid_sms.predict_proba(vec)[0][1]
    label = "SCAM (Spam)" if spam_proba >= threshold else "HAM (Not Scam)"
    print("📩 Message:")
    print(message)
    print("\n🔍 Prediction:")
    print(f"{label} | Confidence: {round(spam_proba*100, 2)}%")
    # --- Risk level (human friendly) ---
    if spam_proba >= 0.6:
        print("⚠️ Risk Level: HIGH RISK SCAM")
    elif spam_proba >= 0.4:
        print("⚠️ Risk Level: LIKELY SCAM")
    else:
        print("✅ Risk Level: LOW RISK")
    # --- LIME explanation ---
    explainer = LimeTextExplainer(class_names=['Ham', 'Spam'])
    def predict_fn(texts):
        texts_cleaned = [clean_text(t) for t in texts]
        texts_vec = tfidf_sms.transform(texts_cleaned)
        return hybrid_sms.predict_proba(texts_vec)
    exp = explainer.explain_instance(
        message,
        predict_fn,
        num_features=8
    )
    print("\n🧠 Why this prediction?")
    for word, weight in exp.as_list():
        effect = "↑ Scam likelihood" if weight > 0 else "↓ Scam likelihood"
        print(f"- '{word}' : {effect}")
    # Optional: visual explanation in notebook
    exp.show_in_notebook()
predict_sms_feature(
    "Congratulations! You have won a free mobile. Click the link now!"
)

from lime.lime_text import LimeTextExplainer
def predict_email_feature(message, threshold=0.5):
    # --- Vectorize email ---
    cleaned = clean_text(message)
    vec = tfidf_email.transform([cleaned])
    # --- Prediction ---
    phish_proba = hybrid_email.predict_proba(vec)[0][1]
    label = "PHISHING (Scam)" if phish_proba >= threshold else "SAFE EMAIL"
    print("📧 Email Message:")
    print(message)
    print("\n🔍 Prediction:")
    print(f"{label} | Confidence: {round(phish_proba*100, 2)}%")
    # --- Risk level ---
    if phish_proba >= 0.7:
        print("⚠️ Risk Level: HIGH RISK PHISHING")
    elif phish_proba >= 0.5:
        print("⚠️ Risk Level: LIKELY PHISHING")
    else:
        print("✅ Risk Level: LOW RISK")
    # --- LIME explanation ---
    explainer = LimeTextExplainer(
        class_names=['Safe Email', 'Phishing Email']
    )
    def predict_fn(texts):
        texts_cleaned = [clean_text(t) for t in texts]
        texts_vec = tfidf_email.transform(texts_cleaned)
        return hybrid_email.predict_proba(texts_vec)
    exp = explainer.explain_instance(
        message,
        predict_fn,
        num_features=8
    )
    print("\n🧠 Why this prediction?")
    for word, weight in exp.as_list():
        effect = "↑ Phishing likelihood" if weight > 0 else "↓ Phishing likelihood"
        print(f"- '{word}' : {effect}")
    # Optional notebook visualization
    exp.show_in_notebook()
predict_email_feature("Your account has been suspended. Verify immediately by clicking this link.")

import pickle

pickle.dump(hybrid_sms, open("hybrid_sms.pkl", "wb"))
pickle.dump(tfidf_sms, open("tfidf_sms.pkl", "wb"))

pickle.dump(hybrid_email, open("hybrid_email.pkl", "wb"))
pickle.dump(tfidf_email, open("tfidf_email.pkl", "wb"))